CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY NOT NULL,
  value TEXT NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text TEXT NOT NULL,
  source TEXT NOT NULL,
  created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS dictionary_terms (
  term TEXT PRIMARY KEY NOT NULL,
  replacement TEXT,
  created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS style_profiles (
  name TEXT PRIMARY KEY NOT NULL,
  instructions TEXT NOT NULL,
  created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS provider_telemetry (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  provider TEXT NOT NULL,
  latency_ms INTEGER NOT NULL,
  success INTEGER NOT NULL,
  created_at INTEGER NOT NULL
);
